package fr.cnam.nfe102.cashcalendar.modele;
// Generated 13 janv. 2016 08:19:32 by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Calendrier generated by hbm2java
 */
@Entity
@Table(name = "calendrier")
public class Calendrier implements java.io.Serializable {

	private Integer idCalendrier;
	private Produit produit;
	private Utilisateur utilisateur;
	private Date jour;
	private Boolean disponible;

	public Calendrier() {
	}

	public Calendrier(Produit produit) {
		this.produit = produit;
	}

	public Calendrier(Produit produit, Utilisateur utilisateur, Date jour, Boolean disponible) {
		this.produit = produit;
		this.utilisateur = utilisateur;
		this.jour = jour;
		this.disponible = disponible;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idCalendrier", unique = true, nullable = false)
	public Integer getIdCalendrier() {
		return this.idCalendrier;
	}

	public void setIdCalendrier(Integer idCalendrier) {
		this.idCalendrier = idCalendrier;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade=CascadeType.ALL)
	@JoinColumn(name = "idProduit")
	public Produit getProduit() {
		return this.produit;
	}

	public void setProduit(Produit produit) {
		this.produit = produit;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade=CascadeType.ALL)
	@JoinColumn(name = "idUtilisateur")
	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "jour", length = 10)
	public Date getJour() {
		return this.jour;
	}

	public void setJour(Date jour) {
		this.jour = jour;
	}

	@Column(name = "disponible")
	public Boolean getDisponible() {
		return this.disponible;
	}

	public void setDisponible(Boolean disponible) {
		this.disponible = disponible;
	}

}
