package fr.cnam.nfe102.cashcalendar.modele;
// Generated 13 janv. 2016 08:19:32 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Produit generated by hbm2java
 */
@Entity
@Table(name = "produit")
public class Produit implements java.io.Serializable {

	private Integer idProduit;
	private String nomProduit;
	private String descriptionProduit;
	private Double prix;
	private Set<Calendrier> calendriers = new HashSet<Calendrier>(0);

	public Produit() {
	}

	public Produit(String nomProduit, String descriptionProduit, Double prix, Set<Calendrier> calendriers) {
		this.nomProduit = nomProduit;
		this.descriptionProduit = descriptionProduit;
		this.prix = prix;
		this.calendriers = calendriers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idProduit", unique = true, nullable = false)
	public Integer getIdProduit() {
		return this.idProduit;
	}

	public void setIdProduit(Integer idProduit) {
		this.idProduit = idProduit;
	}

	@Column(name = "nomProduit", length = 10)
	public String getNomProduit() {
		return this.nomProduit;
	}

	public void setNomProduit(String nomProduit) {
		this.nomProduit = nomProduit;
	}

	@Column(name = "descriptionProduit", length = 100)
	public String getDescriptionProduit() {
		return this.descriptionProduit;
	}

	public void setDescriptionProduit(String descriptionProduit) {
		this.descriptionProduit = descriptionProduit;
	}

	@Column(name = "prix", precision = 22, scale = 0)
	public Double getPrix() {
		return this.prix;
	}

	public void setPrix(Double prix) {
		this.prix = prix;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produit")
	public Set<Calendrier> getCalendriers() {
		return this.calendriers;
	}

	public void setCalendriers(Set<Calendrier> calendriers) {
		this.calendriers = calendriers;
	}

}
