package fr.cnam.nfe102.cashcalendar.modele;
// Generated 13 janv. 2016 08:19:32 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Utilisateur generated by hbm2java
 */
@Entity
@Table(name = "utilisateur")
public class Utilisateur implements java.io.Serializable {

	private Integer idUtilisateur;
	private String mail;
	private String motDePasse;
	private Double solde;
	private Set<Calendrier> calendriers = new HashSet<Calendrier>(0);

	public Utilisateur() {
	}

	public Utilisateur(String mail, String motDePasse, Double solde, Set<Calendrier> calendriers) {
		this.mail = mail;
		this.motDePasse = motDePasse;
		this.solde = solde;
		this.calendriers = calendriers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idUtilisateur", unique = true, nullable = false)
	public Integer getIdUtilisateur() {
		return this.idUtilisateur;
	}

	public void setIdUtilisateur(Integer idUtilisateur) {
		this.idUtilisateur = idUtilisateur;
	}

	@Column(name = "mail", length = 50)
	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	@Column(name = "motDePasse", length = 32)
	public String getMotDePasse() {
		return this.motDePasse;
	}

	public void setMotDePasse(String motDePasse) {
		this.motDePasse = motDePasse;
	}

	@Column(name = "solde", precision = 22, scale = 0)
	public Double getSolde() {
		return this.solde;
	}

	public void setSolde(Double solde) {
		this.solde = solde;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "utilisateur")
	public Set<Calendrier> getCalendriers() {
		return this.calendriers;
	}

	public void setCalendriers(Set<Calendrier> calendriers) {
		this.calendriers = calendriers;
	}

}
